# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: my-configmap
#   namespace: default
# data:
#   my_key: my_value
# ---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-application-set
  namespace: argocd # Make sure Argo CD is installed in this namespace
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://github.com/yashwantmahawar/argo_and_crossplane
  template:
    metadata:
      name: demo-application-{{ cluster }} # Name will be my-app-cluster1, my-app-cluster2, etc.
    spec:
      project: default  # Replace with your Argo CD project name
      source:
        repoURL: "{{ url }}"
        targetRevision: HEAD
        path: argocd/application-sets/  # Path to your Kubernetes manifests within the repository
        directory:
         recurse: true
         jsonnet: {}
        #  exclude: '{**/argocd/application-sets/root/*}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd  # Replace with your desired namespace
      syncPolicy:
        automated: 
          prune: false
          selfHeal: false