apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: crossplane-providers
 namespace: crossplane-system
spec:
 project: default
 source:
   repoURL: 'https://github.com/yashwantmahawar/argo_and_crossplane'
   targetRevision: HEAD
   path: 'argocd/crossplane/providers'
 destination:
   server: 'https://kubernetes.default.svc'
   namespace: crossplane-system
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true