---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgkeclusters.container.gcp.abc.io
spec:
  group: container.gcp.abc.io
  names:
    kind: GKECluster
    singular: xgkecluster
    plural: xgkeclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                # size:
                #   type: string
                #   enum:
                #   - small
                #   - medium
                #   - large
