apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgkeclusters.container.gcp.abc.io
spec:
  compositeTypeRef:
    apiVersion: container.gcp.abc.io/v1alpha1
    kind: XGKECluster
  resources:
    - name: cluster
      base:
        apiVersion: container.gcp.upbound.io/v1beta1
        kind: Cluster
        metadata:
          annotations:
            crossplane.io/external-name: # patched
          labels:
            testing.upbound.io/example-name: cluster
          name: cluster
        spec:
          forProvider:
            deletionProtection: false
            enableAutopilot: true
            enableIntranodeVisibility: true
            ipAllocationPolicy:
              - {}
            location: europe-west2 # patched
            #initialNodeCount: # patched
            # ipAllocationPolicy:
            #   - servicesSecondaryRangeName: services
            #     clusterSecondaryRangeName: pods
            # networkSelector:
            #   matchLabels: {} # patched
            # subnetworkSelector:
            #   matchLabels: {} # patched
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.location"
        # - fromFieldPath: "spec.size"
        #   toFieldPath: "spec.nodeConfig.machineType"
        #   transforms:
        #     - type: string
        #       string:
        #         type: Switch
        #         switch:
        #           - condition: "input == 'small'"
        #             output: "e2-standard-2"
        #           - condition: "input == 'medium'"
        #             output: "e2-standard-4"
        #           - condition: "input == 'large'"
        #             output: "e2-standard-8"
        #           - output: "e2-standard-2" # Default value
      # readinessChecks:
      #   - type: NonEmpty
      #     fieldPath: status.conditions[?(@.type=='Ready')].status
      #     condition: "True"